gui:
  nerdFontsVersion: '2'
  # splitDiff: 'always'
  sidePanelWidth: 0.2
git:
  paging:
    colorArg: 'always'
    pager: delta --dark --paging=never
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} -- {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim {{dir}}'
