git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: 'vim {{filename}}'
  editAtLine: 'vim +{{line}} -- {{filename}}'
  editInTerminal: true
  openDirInEditor: 'vim {{dir}}'
